const jwt = require('jsonwebtoken');

function requireAuthentication(req, res, next) {
    const token = req.cookies?.token;

    if (!token) {
        return res.status(401).json({
            error: {
                code: 'UNAUTHORIZED',
                message: 'Authentication required',
                correlationId: req.correlationId
            }
        });
    }

    const jwtSecret = process.env.JWT_SECRET;
    if (!jwtSecret) {
        console.error('JWT_SECRET is missing');
        return res.status(500).json({
            error: {
                code: 'INTERNAL_ERROR',
                message: 'Internal configuration error',
                correlationId: req.correlationId
            }
        });
    }

    try {
        const decoded = jwt.verify(token, jwtSecret);
        
        // 4. Build the principal
        // 5. Attach the principal to the request context
        // The decoded payload contains principal_type, principal_id, and role (generated by Node.js).
        // It is trusted and cannot be overridden by client request body/headers.
        req.principal = {
            principal_type: decoded.principal_type,
            principal_id: decoded.principal_id,
            role: decoded.role
        };

        next();
    } catch (err) {
        return res.status(401).json({
            error: {
                code: 'UNAUTHORIZED',
                message: 'Invalid or expired token',
                correlationId: req.correlationId
            }
        });
    }
}

module.exports = {
    requireAuthentication
};
